### PR TITLE
feat: join utility

### PR DESCRIPTION
**Pull request by eranhirsch**
Adding a better typed wrapper around the builtin Array.prototype.join, with data-first and data-last signatures.

Similar to https://github.com/sindresorhus/type-fest/blob/main/source/join.d.ts

---

Make sure that you:

- [x] Typedoc added for new methods and updated for changed
- [x] Tests added for new methods and updated for changed
- [x] New methods added to `src/index.ts`
- [x] New methods added to `mapping.md`

### CODE REVIEW

**Review by TkDodo — APPROVED** [review]

**Comment by TkDodo** [comment]
seems like this feature doesn't work with TS 4.4, but works with 4.8 ?

**Comment by eranhirsch** [comment]
Good thing we have the new tests, i'll check it out

**Comment by TkDodo** [comment]
> Good thing we have the new tests

my thoughts exactly

**Comment by TkDodo** [comment]
I think 4.7 and onwards is fine, and we can set stricter standards (like > 5.0) in a new major

**Review by TkDodo — APPROVED** [review]

**Pull request merged**
