### PR TITLE
feat: Add zipObj

### PR DESCRIPTION
**Pull request by itelo**
Resolves (https://github.com/remeda/remeda/issues/72)

---

Make sure that you:

- [x] Typedoc added for new methods and updated for changed
- [x] Tests added for new methods and updated for changed
- [x] New methods added to `src/index.ts`
- [x] New methods added to `mapping.md`

### CODE REVIEW

**Review by TkDodo — APPROVED** [review]

**Comment by TkDodo** [comment]
@itelo can you have a look at why the data-last tests are failing please?

**Comment by yanick** [comment]
> @itelo can you have a look at why the data-last tests are failing please?

seems the test was (erroneously) expected arrays, not objects. A patch is available at https://github.com/yanick/remeda/tree/feature/zipObj

**Comment by TkDodo** [comment]
thanks @yanick ❤️

**Pull request merged**
