### PR TITLE
feat(build): use tsup for building

### PR DESCRIPTION
**Pull request by eranhirsch**
! I'm not sure that tsup is doing what we want it to do: we are outputing a single file that contains all utility functions.

As far as I understand it, that means that the project wouldn't be tree-shakable and thus would cause users to have to import everything.

Based on #360

### CODE REVIEW

**Comment by eranhirsch** [comment]
@TkDodo, from your understanding of tree-shaking, is this build process going to break tree-shaking?

**Comment by eranhirsch** [comment]
So this definitely breaks tree-shaking. I'll play around with it and see if there's a way to fix it. @TkDodo, do you have any ideas? Is there anyone that can help us with this?

image

**Comment by cjquines** [comment]
why did we want to use tsup again? isnt the existing build like, fine

**Comment by eranhirsch** [comment]
When running publint on v1 you can see that the build isn't perfect. It's both a little complex and requires us to run typescript 3 times with different settings which is brittle. I think the hope at least was that tsup would take the minutiae of building from us so we don't need to be concerned with esm and cjs shenanigans.

**Comment by eranhirsch** [comment]
See #347

**Pull request merged**
