### PR TITLE
chore(ts): Upgrade typescript to 5.7 and add it to the testing matrix

### PR DESCRIPTION
**Pull request by eranhirsch**

### CODE REVIEW

**Comment by eranhirsch** [comment]
@cjquines - I couldn't figure out what the issue is with the failing type tests. I checked if updating vitest helps but it was only a patch version bump and it didn't help. Do you have any idea what might be the issue here?

**Comment by eranhirsch** [comment]
nvm - https://devblogs.microsoft.com/typescript/announcing-typescript-5-7/#typedarrays-are-now-generic-over-arraybufferlike

**Comment by cjquines** [comment]
hm, but now it's failing the lower version typetests…

**Comment by eranhirsch** [comment]
Fixed as part of #939, checkout https://github.com/remeda/remeda/pull/939/files#r1875847152

**Pull request closed without merging**
