### PR TITLE
build: update deps and configure dependabot

### PR DESCRIPTION
**Pull request by eranhirsch**
Bumping all our dependencies to the latest version and configuring dependabot to keep us updated on a monthly basis. This should prevent us from drifting too much, making it easier to adopt the latest versions incrementally, and allowing us to benefit from the eco system moving forward.

Changes in the source itself was due to prettier changes since 2.8

### CODE REVIEW

**Comment by eranhirsch** [comment]
Will wait with this till after #374

**Comment by TkDodo** [comment]
hmm, something seems wrong here:

```
⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
Error: Failed to load @vitest/coverage-c8. Default export is missing.
```

**Comment by eranhirsch** [comment]
Might require a rebase, I remember seeing this issue lately

**Comment by TkDodo** [comment]
> Might require a rebase, I remember seeing this issue lately

branch is up-to-date with latest master

**Comment by eranhirsch** [comment]
hey @TkDodo, check out the weird bug I'm getting with this version with SyntaxHighlighter in docs/src/CodeBlock.tsx... I don't understand what's happening here... it's very odd...

I might have time to go over it this week, but in the meantime wanted to ping you to see what you think

**Comment by eranhirsch** [comment]
ping @TkDodo ?

**Review by TkDodo — APPROVED** [review]

**Pull request merged**
