### PR TITLE
chore(deps): bump versions

### PR DESCRIPTION
**Pull request by eranhirsch**
This includes minor updates to:

* typescript 4.7 -> 4.9, providing some neat typing improvements, perf benefits, and the satisifies operator
* prettier fixes, basically to support satisfies, and minor fixes.

* vitest - I don't know what changed, seem like bugfix updates

Tested:
```bash
yarn lint
yarn prettier
yarn test
```

### CODE REVIEW

**Comment by TkDodo** [comment]
> typescript 4.7 -> 4.9, providing some neat typing improvements, perf benefits, and the satisifies operator

I'm not so sure about that one. Please keep in mind that we probably shouldn't use latest TS features. There is no real policy here (maybe we should have one?) but if we start to use TS 4.9 features, it means that our consumers must also be on TS4.9 (unless we provide differential typings for different TS versions, which is possible, but harder to maintain).

I actually don't know what the current minimum version of TS is that we need. There is something going on in this PR where we talked about needing 4.7 at a minimum:

- https://github.com/remeda/remeda/pull/222#discussion_r1020774509

**Comment by eranhirsch** [comment]
Those are really good points i didn't think about. I wonder how the TS team see this, there are advantages to the dev experience using the latest TS which would be odd to deny from package maintainers that want a broad user-base. Are there any compatibility mode flags in the tsconfig file that could be used to lock the output version?

**Comment by TkDodo** [comment]
the only thing I know of is shipping different types depending on the typescript version like so: https://github.com/TanStack/query/blob/5e37b145a8836b00dd20860e8eb1f94c608fec81/package.json#L83-L85

the thing is, if we update the requirements in a minor, the lib will likely break for users that have a smaller TS version. In react-query, we only increment those requirements in majors. With the next one, we'll go from at leat 4.1 to at least 4.7. But it will be some time until we can use `satisfies` (4.9) or const inference (5.0) ...

**Comment by eranhirsch** [comment]
Ok, so this isn't really important for now...

**Comment by airjp73** [comment]
> I actually don't know what the current minimum version of TS is that we need. There is something going on in this PR where we talked about needing 4.7 at a minimum:
> 
> https://github.com/remeda/remeda/pull/222#discussion_r1020774509

Yeah, in one of the earlier versions of the PR I was using the `extends` keyword after an `infer` (e.g. `infer Foo extends string`). The current iteration doesn't need that at all.

**Pull request closed without merging**
