### PR TITLE
feat(toSnakeCase): add toSnakeCase

### PR DESCRIPTION
**Pull request by filipw01**
Added toSnakeCase function

Related issue: https://github.com/remeda/remeda/issues/457

The js implementation is fairly simple, but I struggle with types a bit. Type-fest has `SnakeCase` but as visible in the tests it has some issues. Using `SnakeCase<CamelCase<T, { preserveConsecutiveUppercase: true }>>` was yielding much better effects, but it is not ideal. We'll probably need to make a PR to `type-fest` but I'm optimistic that it can be done with an implementation more similar to CamelCase but tailored for SnakeCase

---

Make sure that you:

- [x] Typedoc added for new methods and updated for changed
- [x] Tests added for new methods and updated for changed
- [x] New methods added to `src/index.ts`
- [x] New methods added to `docs/src/content/mapping` for both Lodash and Ramda.

---

<details><summary>We use semantic PR titles to automate the release process!</summary>

https://conventionalcommits.org

PRs should be titled following using the format: `< TYPE >(< scope >)?: description`

### Available Types:

- `feat`: new functions, and changes to a function's type that would impact users.
- `fix`: changes to the runtime behavior of an existing function, or refinements to it's type that shouldn't impact most users.
- `perf`: changes to function implementations that improve a functions _runtime_ performance.
- `refactor`: changes to function implementations that are neither `fix` nor `perf`
- `test`: tests-only changes (transparent to users of the function).
- `docs`: changes to the documentation of a function **or the documentation site**.
- `build`, `ci`, `style`, `chore`, and `revert`: are only relevant for the internals of the library.

For scope put the name of the function you are working on (either new or
existing).

</details>

### CODE REVIEW

**Comment by filipw01** [comment]
https://github.com/sindresorhus/type-fest/pull/930

There's also an open question what should happen when there are numbers in the string, I guess we can follow whatever is decided in type-fest

**Comment by eranhirsch** [comment]
I'm not sure your issue with type-fest covers the main problem with this type, that it returns a union of possible definitions of snake_case, and not a single value, e.g. for the input "parseHTML" the type-fest type accepts more than one possible interpretation of snake_case, which is not good for a return type:

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgZQHYEMDWBTAwugZ2zgF84AzKCEOAIhgE8xsBac7AmWgbgChfGzOAEEAjHAC8KDDnxEAPLTDooRABIAVALIAZWgD4+AeiNwzAPQD8QA

**Comment by filipw01** [comment]
This particular case is covered 😉  So as long as my PR is merged in type-fest we can progress with this one

**Comment by eranhirsch** [comment]
With #924 now providing better types for snake and kebab cases, is there anything this PR aims to do that still needs to be provided? It looks like the type-fest PRs are stuck, and I'm not sure it's still worthwhile pursuing.

**Comment by filipw01** [comment]
I think this PR is no longer needed. The only addition I can think of adding is to support not splitting on numbers like here in the test cases at the bottom https://github.com/sindresorhus/type-fest/pull/930/files#diff-1dfa4b7476785567bfe17d478e30cf2b76fffc23fe49ba264f08b95473fe073d

We could revisit this after type-fest PRs are merged around this, but I'll close this one

**Comment by eranhirsch** [comment]
Thanks for your involvement!

**Pull request closed without merging**
