### PR TITLE
feat(groupBy): add support for generic key types

### PR DESCRIPTION
**Pull request by eranhirsch**
`groupBy` currently doesn't support refined types for it's grouper function, so you lose typing information in cases where those are available.

This diff only touches typing, and doesn't change anything in the runtime behaviour of the function.

It maintains backwards compatibility by still returning `Record<string, T>` if the grouper function returns a string. And for literal unions it will return a Partial record.

I tried adding tests, and they do provide some protection, but I'm not sure I'm using AssertEqual correctly, as it doesn't fail on the wrong types (sometimes). I validated manually via the IDE that the types returned are correct. 

Fixes: #262

---

Make sure that you:

- [?] Typedoc added for new methods and updated for changed
- [+] Tests added for new methods and updated for changed
- [-] New methods added to `src/index.ts`
- [-] New methods added to `mapping.md`

### CODE REVIEW

**Comment by TkDodo** [comment]
👍 can you please fix the formatting?

**Comment by eranhirsch** [comment]
@TkDodo - should the better typing actually be implemented as a `strict` version of groupBy. My thoughts on this are that it can go either way. It would keep the existing logic backwards compatible for those already relying on it, but the downside is that it's redundant because it's achievable by widening the type of the grouper function to `string` or `number`.

**Comment by TkDodo** [comment]
@eranhirsch yeah I like the idea of doing a `strict` version of that 👍

**Comment by eranhirsch** [comment]
@TkDodo - I've moved the new typing to a strict variant

**Review by TkDodo — APPROVED** [review]

**Pull request merged**
