### PR TITLE
refactor(mean): drop `bigint` support

### PR DESCRIPTION
**Pull request by grigorischristainas**
Related to #874, I have also integrated changes based on recent comments about `median` (e.g., removed type-guard related tests and modified the `Mean` type)

Please let me know if any additional adjustments are needed.

### CODE REVIEW

**Review by cjquines — APPROVED** [review]

**Comment by cjquines** [comment]
technically a breaking change, but i'm fine shipping this as `fix`

**Comment by eranhirsch** [comment]
This didn't cause a release because we only release on "fix" and "feat"... we should drop the "refactor" label as it isn't helpful.

**Comment by cjquines** [comment]
i think `refactor` and `chore` shouldn't trigger a release, but yeah

**Pull request merged**
