### PR TITLE
feat(multisets): add difference, union, intersect, isContains, symmetric difference (xor), and isEqual

### LINKED ISSUE #363: feature request: xor
I would love it if this library had methods analogous to xor from lodash (https://lodash.com/docs/4.17.15#xor).

### PR DESCRIPTION
**Pull request by eranhirsch**
Adding multi-set functions:
- [x] Difference
- [x] Union
- [x] Intersect
- [x] IsContains
- [x] Symmetric Difference ("XOR")
- [x] isEqual 
- ~~isDisjoint~~ (this doesn't have any multiset specific impl concerns)

Closes #363

---

Make sure that you:

- [x] Typedoc added for new methods and updated for changed
- [x] Tests added for new methods and updated for changed
- [x] New methods added to `src/index.ts`

### CODE REVIEW

**Comment by eranhirsch** [comment]
I have some ideas about how to get this API right, I want to drop the multiset names and just rename the regular functions, i'll send out smaller PRs in the near future

**Comment by mwarger** [comment]
@eranhirsch Just curious about this one - any luck?

**Comment by eranhirsch** [comment]
It's a busy period for me and I didn't get around to doing this. You can see it's a pretty big change if we want to cover all the cases, i want to split this into smaller parts but I just didn't find the time yet.

**Comment by eranhirsch** [comment]
difference and intersection are now part of v1 as a variant (`difference.multiset` and `intersection.multiset`), and in v2 as the only implementation.

Other functions would be added directly to v2 after release.

**Pull request closed without merging**
