### PR TITLE
feat: Add R.add, R.subtract, R.multiply and R.divide functions

### LINKED ISSUE #439: Add `add` and `multiply` functions.
These simple functions add and multiply two numbers.

This is useful when determining `sums` and `products` of arrays of numbers.

```
[1, 2, 3, 4].reduce(R.add); // 10
[1, 2, 3, 4].reduce(R.multiply); // 24
```

For completeness, it might also be worth adding `subtract` and `divide`.

All four functions are implemented in both Lodash and Ramda.

Separately, `sum` and `product` functions could also be useful. There's currently a `sumBy` function in Remeda, so `R.sum` could be as simple as `R.sumBy(R.identity)`.

### PR DESCRIPTION
**Pull request by LandonSchropp**
This PR introduces four new number functions: `R.add`, `R.subtract`, `R.multiply` and `R.divide`.

Closes #439.

---

Make sure that you:

- [x] Typedoc added for new methods and updated for changed
- [x] Tests added for new methods and updated for changed
- [x] New methods added to `src/index.ts`
- [x] New methods added to `mapping.md`

---

<details><summary>We use semantic PR titles to automate the release process!</summary>

https://conventionalcommits.org

PRs should be titled following using the format: `< TYPE >(< scope >)?: description`

### Available Types:

- `feat`: new functions, and changes to a function's type that would impact users.
- `fix`: changes to the runtime behavior of an existing function, or refinements to it's type that shouldn't impact most users.
- `perf`: changes to function implementations that improve a functions _runtime_ performance.
- `refactor`: changes to function implementations that are neither `fix` nor `perf`
- `test`: tests-only changes (transparent to users of the function).
- `docs`: changes to the documentation of a function **or the documentation site**.
- `build`, `ci`, `style`, `chore`, and `revert`: are only relevant for the internals of the library.

For scope put the name of the function you are working on (either new or
existing).

</details>

### CODE REVIEW

**Comment by LandonSchropp** [comment]
@eranhirsch I started with `R.add`. Let me know if it works for you and I'll add the others to this PR. 😎

**Comment by eranhirsch** [comment]
This looks great, can you add the other functions from the title?

**Comment by LandonSchropp** [comment]
@eranhirsch This should be ready to go.

**Review by TkDodo — APPROVED** [review]

**Pull request merged**
